print("Hello World!")
print("My name is Liza")
print("Whats your name?")
name_user=input()
print("Nice to meet you, " + name_user)
print("Do you like this place?")
question=input()
print("Ohh, me too...")
print("Okey, Goodbye!")
